# .github/workflows/save_data.yml

name: Daily Crypto Data Save

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 12 AM UTC
  workflow_dispatch: {}

jobs:
  save-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # Important: Pour committer des changements, l'action de checkout a besoin d'un token avec permissions d'écriture.
        # Par défaut, GITHUB_TOKEN a des permissions limitées en lecture.
        # Nous allons le configurer plus bas dans les permissions du job.

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data fetching and saving script
        run: |
          python -m src.fetch_and_save
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Commit and push new data # Nouvelle étape : commit et push les données générées
        run: |
          git config user.name "github-actions[bot]" # Configure l'utilisateur Git pour le commit
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/crypto_data_*.json # Ajoute tous les nouveaux fichiers JSON de données
          timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC") # Obtient l'horodatage actuel
          git commit -m "feat(data): Add daily crypto data for ${timestamp}" || echo "No changes to commit" # Commit les changements, ignore si pas de nouveau fichier
          git push # Pousse les changements vers le dépôt distant
        env:
          # Le GITHUB_TOKEN est automatiquement fourni par GitHub Actions et a les permissions nécessaires
          # s'il est configuré au niveau du job.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# --- Nouvelle section : Permissions pour le job ---
permissions:
  contents: write # Accorde la permission d'écriture pour le contenu du dépôt au job 'save-data'